### ISSUE TITLE
framebuffer-patch-enable and framebuffer-stolenmem must be data type

### ISSUE THREAD

**Issue by ggrossman** [walteweiss/Hackintosh-GA-Z87MX-D3H#1]
Hi @walteweiss , thanks for uploading your setup! I was able to quickly get my old Z87MX-D3H build from Clover to OpenCore using it. One small note, there's a minor error in your iGPU section:

```
				<key>framebuffer-patch-enable</key>
				<string>01000000</string>
				<key>framebuffer-stolenmem</key>
				<string>00003001</string>
```

I can see in the boot logs that it can't parse `framebuffer-patch-enable`. It expects this to be type `data`, not type `string`.

I was able to fix it with

```
                                <key>framebuffer-patch-enable</key>
                                <data>AQAAAA==</data>
                                <key>framebuffer-stolenmem</key>
                                <data>AAAwAQ==</data>
```

(I also had to change `ig-platform-id` to 0x0300220D since I'm not using a dGPU.)

**Comment by walteweiss** [comment]
Hi @ggrossman,

You are very welcome and I’m happy I helped someone by just sharing my config files! I plan to keep this config updated as long as I use it, and at this point it meets all my needs, so I expect for this machine to kick for at least 5 more years. 

As of the error, at first thank you so much for your contribution! I had no idea I had it.

Do you mind sharing how do you check boot logs? I turned off logging completely after I saw no errors, I could be very wrong at this point and I have errors.

**Comment by walteweiss** [comment]
As of [the guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html#add-2) I may not need to have all this, since I have dGPU. But I’m not sure on this.

**Comment by walteweiss** [comment]
Yesterday’s evening I was puzzled on how to properly convert values from Xcode ones to vim-like — e.g. why `01000000` becomes `AQAAAA== ` — I remember I converted the value, but I forgot from where to where.

As I saw a string of 0s and 1s, I thought it’s binary type, so I converted from `binary` to `base64` and it gave me very different result. **Turned out it’s not `binary` to `base64` conversion, but `hex` to `base64` conversion.**

There are web converters for that, like:

- https://base64.guru/converter/encode/hex
- https://cryptii.com/pipes/hex-to-base64
